

//===============================================================================
//                                   Constants
//===============================================================================
def FAILED_STAGE
def APP_CONTAINER_NAME = "web_app_container"
def APP_IMAGE_NAME = "web_application_img:latest"
def HOST_PORT = "5000"
def APP_PORT = "5000"
def APP_FOLDER = "application"
def HOST_ADDRESS = "localost"
//===============================================================================
//                                   PIPELINE
//===============================================================================
pipeline {
    agent { label 'docker-agent' }
    //environment {
		//DOCKERHUB_CREDENTIALS=credentials('Docker_Hub')
	 //}    
    stages {          
        stage('Remove Old Web Application Docker Container...') {
            steps { 
                script {
                    FAILED_STAGE=env.STAGE_NAME
                    echo '''-------------------------------------------------------------------------------- 
                      * Stratus Project Pipeline Start! *             
--------------------------------------------------------------------------------'''
                    echo "Stage: ${STAGE_NAME}"
                    sh '''
                        echo "[INFO] Existing containers:"
                        docker ps -a
                        echo "[INFO] Removing old ${APP_CONTAINER_NAME} if exists..."
                        docker ps -a --format '{{.Names}}' | grep -w ${APP_CONTAINER_NAME} && docker rm -f ${APP_CONTAINER_NAME} || echo "Container not found."
                        echo "[INFO] Cleaning up unused resources..."
                        docker system prune -f || true
                        echo "[INFO] Remaining containers:"
                        docker ps
                    '''
                } 
            }
        }
    ////////////////////////////////////////////////////////////////////////////////          
        stage('Build New Web Application Docker Image') {
            steps { 
                script {
                    FAILED_STAGE=env.STAGE_NAME
                    echo "Stage: ${STAGE_NAME}"
                    sh '''
                        pwd
                        cd application
                        ls -la
                        docker images
                        docker build . -t web_application_img:latest
                        docker images  
                        '''
                }
            } 
        } 			
    ////////////////////////////////////////////////////////////////////////////////       
        stage('Deploy Web Application') {
            steps { 
                script {
                    FAILED_STAGE=env.STAGE_NAME
                    echo "Stage: ${STAGE_NAME}"
                    sh '''
                        docker ps
                        docker run -d -p 5000:5000 --name web_app_container web_application_img:latest
                        docker ps
                    '''
                }
            } 
        }
   	////////////////////////////////////////////////////////////////////////////////		
        
        stage('Weather App Unittest') {
            steps { script {
                FAILED_STAGE=env.STAGE_NAME
                echo "Stage: ${STAGE_NAME}"
                // sh 'python3 test_unit.py'
            }}
        }
        stage('Upload to DockerHub') {
            steps { script {
                FAILED_STAGE=env.STAGE_NAME
                echo "Stage: ${STAGE_NAME}"            
                // sh 'echo $DOCKERHUB_CREDENTIALS_PSW | sudo docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                // sh 'sudo docker push 310179635/weather_app_img'
                
                echo '''-------------------------------------------------------------------------------- 
                             * Uploading Done :) ! *           
--------------------------------------------------------------------------------'''
                
            } }
        }

        stage('Pipeline Finished!') {
            steps { script {
                FAILED_STAGE=env.STAGE_NAME
                echo '''-------------------------------------------------------------------------------- 
                      * Stratus Project Pipeline Ended! *             
--------------------------------------------------------------------------------'''
				
            } }
        }
    }
    post {
        success {
                mail to: "brozenman@gmail.com",
                subject: "JENKINS PIPELINE: ${currentBuild.currentResult} - ${env.JOB_NAME}",
                body: "JOB NAME: ${env.JOB_NAME}\nPIPELINE STATUS: ${currentBuild.currentResult}\nCOMMIT ID: ${env.GIT_COMMIT}\n ${env.BUILD_URL} "
                }
        failure {
                mail to: "brozenman@gmail.com",
                subject: "JENKINS PIPELINE: ${currentBuild.currentResult} - ${env.JOB_NAME}",
                body: "JOB NAME: ${env.JOB_NAME}\nSTAGE FAILED NAME: $FAILED_STAGE \nPIPELINE STATUS: ${currentBuild.currentResult}\nCOMMIT ID: ${env.GIT_COMMIT}\n ${env.BUILD_URL} "
                }       
    }
}

