//===============================================================================
// Boris Rozenman (c). 
// 
// Python Web Application Pipeline
// Deploy on local environment simulating a whole CI/CD
//===============================================================================

//===============================================================================
//                                   Variables
//===============================================================================
def FAILED_STAGE

//===============================================================================
//                                   PIPELINE
//===============================================================================
pipeline {
    agent { label 'docker-agent' }
    parameters {
        string(name: 'SMOKE_TEST_ADDRESS', defaultValue: 'localhost', description: 'Target address for smoke test')
        string(name: 'SMOKE_TEST_PORT', defaultValue: '5000', description: 'Target port for smoke test')
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('Docker_Hub')
        APP_CONTAINER_NAME = "web_app_container"
        APP_IMAGE_TAG = "web_application_img"
        APP_IMAGE_VER = "${BUILD_NUMBER}"
        HOST_PORT = "${params.SMOKE_TEST_PORT}"
        APP_PORT = "5000"
        APP_FOLDER = "application"
        DOCKER_NETWORK = "jenkins-net"
        DOCKERHUB_USER = "310179635"
        DOCKERHUB_REPO = "stratus"
    }
    ////////////////////////////////////////////////////////////////////////////////
    stages {
        stage('Remove Old Web Application Docker Container...') {
            steps {
                script {
                    FAILED_STAGE = env.STAGE_NAME
                    echo '''-------------------------------------------------------------------------------- 
                      * Stratus Project Pipeline Start! *             
--------------------------------------------------------------------------------'''
                    echo "Stage: ${STAGE_NAME}"
                    sh '''
                        echo "[INFO] Existing containers:"
                        docker ps -a
                        echo "[INFO] Removing old ${APP_CONTAINER_NAME} if exists..."
                        docker ps -a --format '{{.Names}}' | grep -w ${APP_CONTAINER_NAME} && docker rm -f ${APP_CONTAINER_NAME} || echo "Container not found."
                        echo "[INFO] Cleaning up unused resources..."
                        docker system prune -f || true
                        echo "[INFO] Remaining containers:"
                        docker ps
                    '''
                }
            }
        }
        ////////////////////////////////////////////////////////////////////////////////
        stage('Build New Web Application Docker Image') {
            steps {
                script {
                    FAILED_STAGE = env.STAGE_NAME
                    echo "Stage: ${STAGE_NAME}"
                    sh '''
                        pwd
                        cd ${APP_FOLDER}
                        ls -la
                        docker images
                        docker build . -t ${DOCKERHUB_USER}/${DOCKERHUB_REPO}:${APP_IMAGE_TAG}-${APP_IMAGE_VER}
                        docker images
                    '''
                }
            }
        }
        ////////////////////////////////////////////////////////////////////////////////
        stage('Deploy Web Application') {
            steps {
                script {
                    FAILED_STAGE = env.STAGE_NAME
                    echo "Stage: ${STAGE_NAME}"
                    sh '''
                        docker ps
                        docker run -d \
                          --network ${DOCKER_NETWORK} \
                          -p ${HOST_PORT}:${APP_PORT} \
                          --name ${APP_CONTAINER_NAME} \
                          ${DOCKERHUB_USER}/${DOCKERHUB_REPO}:${APP_IMAGE_TAG}-${APP_IMAGE_VER}
                        docker ps
                    '''
                }
            }
        }
        ////////////////////////////////////////////////////////////////////////////////
        stage('Test Web Application') {
            steps {
                script {
                    FAILED_STAGE = env.STAGE_NAME
                    echo "Stage: ${STAGE_NAME}"
                    writeFile file: "${APP_FOLDER}/test_config.json", text: """{
                        "address": "${params.SMOKE_TEST_ADDRESS}",
                        "port": "${params.APP_PORT}"
                        }"""
                    sh '''
                        pwd
                        cd ${APP_FOLDER}
                        ls -la
                        . /opt/venv/bin/activate
                        python3 smoke_test.py
                    '''
                }
            }
        }
        ////////////////////////////////////////////////////////////////////////////////
        stage('Upload to DockerHub') {
            steps {
                script {
                    FAILED_STAGE = env.STAGE_NAME
                    echo "Stage: ${STAGE_NAME}"
                    sh '''
                        echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin
                        docker push ${DOCKERHUB_USER}/${DOCKERHUB_REPO}:${APP_IMAGE_TAG}-${APP_IMAGE_VER}
                    '''
                    echo "Uploading Done!"
                }
            }
        }
        ////////////////////////////////////////////////////////////////////////////////
        stage('Pipeline Finished!') {
            steps {
                script {
                    FAILED_STAGE = env.STAGE_NAME
                    echo '''-------------------------------------------------------------------------------- 
                      * Stratus Project Pipeline Ended! *             
--------------------------------------------------------------------------------'''
                }
            }
        }
    }
    post {
        success {
            mail to: "brozenman@gmail.com",
                 subject: "JENKINS PIPELINE: ${currentBuild.currentResult} - ${env.JOB_NAME}",
                 body: "JOB NAME: ${env.JOB_NAME}\nPIPELINE STATUS: ${currentBuild.currentResult}\nCOMMIT ID: ${env.GIT_COMMIT}\n ${env.BUILD_URL} "
        }
        failure {
            mail to: "brozenman@gmail.com",
                 subject: "JENKINS PIPELINE: ${currentBuild.currentResult} - ${env.JOB_NAME}",
                 body: "JOB NAME: ${env.JOB_NAME}\nSTAGE FAILED NAME: $FAILED_STAGE \nPIPELINE STATUS: ${currentBuild.currentResult}\nCOMMIT ID: ${env.GIT_COMMIT}\n ${env.BUILD_URL} "
        }
    }
}
