//===============================================================================
// Boris Rozenman (c). 
// 
// Python Web Application Pipeline
// Deploy on local environment simulating a whole CI/CD
//===============================================================================

//===============================================================================
//                                   Variables
//===============================================================================
def FAILED_STAGE
def SUBJECT = "Jenkins Pipeline"
def DEFAULT_EMAIL = "brozenman@gmail.com"
def EMAIL_BODY = "Job Name"
def PSTATUS_TAG = "Pipeline Status"
def COMMIT_ID_TAG = "Commit ID"
def FSTAGE_NAME = "Failed in Stage"
def APP_NAME = "weather"
//===============================================================================
//                                   PIPELINE
//===============================================================================
pipeline {
    agent { label 'docker-agent' }
    parameters {
        string(name: 'SMOKE_TEST_ADDRESS', defaultValue: '${APP_NAME}_app_container', description: 'Target address for smoke test, For Containers its the app container name. ')
        string(name: 'SMOKE_TEST_PORT', defaultValue: '5000', description: 'Target port for smoke test')
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('Docker_Hub')
        APP_CONTAINER_NAME = "${APP_NAME}_app_container"
        APP_IMAGE_TAG = "${APP_NAME}_app_img"
        APP_IMAGE_VER = "${BUILD_NUMBER}"
        HOST_PORT = "${params.SMOKE_TEST_PORT}"
        APP_PORT = "5000"
        APP_FOLDER = "application"
        DOCKER_NETWORK = "jenkins-net"
        DOCKERHUB_USER = "310179635"
        DOCKERHUB_REPO = "stratus"
    }
    ////////////////////////////////////////////////////////////////////////////////
    stages {
        stage('Validate Parameters') {
            steps {
                script {
                    FAILED_STAGE = env.STAGE_NAME
                    echo "Stage: ${STAGE_NAME}"
                    if (params.SMOKE_TEST_ADDRESS.isEmpty()) {
                        error "[ERROR] SMOKE_TEST_ADDRESS is empty. Please provide a address."
                    }
                    if (params.SMOKE_TEST_PORT.isEmpty()) {
                        error "[ERROR] SMOKE_TEST_PORT is empty. Please provide a port."
                    }
                    try {
                        Integer.parseInt(params.SMOKE_TEST_PORT)
                    } catch (e) {
                        error "[ERROR] Port ${params.SMOKE_TEST_PORT} is Invalid. Please provide a valid port."
                    }
                    echo "[INFO] Parameters validated successfully."
                }
            }
        }
        
        stage('Remove Old Application Docker Container...') {
            steps {
                script {
                    FAILED_STAGE = env.STAGE_NAME
                    echo '''-------------------------------------------------------------------------------- 
                      * Stratus Project Pipeline Start! *             
--------------------------------------------------------------------------------'''
                    echo "Stage: ${STAGE_NAME}"
                    sh '''
                        echo "[INFO] Existing containers:"
                        docker ps -a
                        echo "[INFO] Removing old ${APP_CONTAINER_NAME} if exists..."
                        docker ps -a --format '{{.Names}}' | grep -w ${APP_CONTAINER_NAME} && docker rm -f ${APP_CONTAINER_NAME} || echo "Container not found."
                        echo "[INFO] Cleaning up unused resources..."
                        docker system prune -f || true
                        echo "[INFO] Remaining containers:"
                        docker ps
                    '''
                }
            }
        }
        ////////////////////////////////////////////////////////////////////////////////
        stage('Build New Application Docker Image') {
            steps {
                script {
                    FAILED_STAGE = env.STAGE_NAME
                    echo "Stage: ${STAGE_NAME}"
                    sh '''
                        pwd
                        cd ${APP_FOLDER}
                        ls -la
                        docker images
                        docker build . -t ${DOCKERHUB_USER}/${DOCKERHUB_REPO}:${APP_IMAGE_TAG}-${APP_IMAGE_VER}
                        docker images
                    '''
                }
            }
        }
        ////////////////////////////////////////////////////////////////////////////////
        stage('Deploy Application') {
            steps {
                script {
                    FAILED_STAGE = env.STAGE_NAME
                    echo "Stage: ${STAGE_NAME}"
                    sh '''
                        docker ps
                        docker run -d \
                          --network ${DOCKER_NETWORK} \
                          -p ${HOST_PORT}:${APP_PORT} \
                          --name ${APP_CONTAINER_NAME} \
                          ${DOCKERHUB_USER}/${DOCKERHUB_REPO}:${APP_IMAGE_TAG}-${APP_IMAGE_VER}
                        docker ps
                    '''
                }
            }
        }
        ////////////////////////////////////////////////////////////////////////////////
        stage('Test Application') {
            steps {
                script {
                    FAILED_STAGE = env.STAGE_NAME
                    echo "Stage: ${STAGE_NAME}"
                    writeFile file: "${APP_FOLDER}/test_config.json", text: """{
                        "address": "${params.SMOKE_TEST_ADDRESS}",
                        "port": "${params.SMOKE_TEST_PORT}"
                        }"""
                    sh '''
                        pwd
                        cd ${APP_FOLDER}
                        ls -la
                        . /opt/venv/bin/activate
                        cat test_config.json
                        python3 smoke_test.py
                    '''
                }
            }
        }
        ////////////////////////////////////////////////////////////////////////////////
        stage('Upload to DockerHub') {
            steps {
                script {
                    FAILED_STAGE = env.STAGE_NAME
                    echo "Stage: ${STAGE_NAME}"
                    sh '''
                        echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin
                        docker push ${DOCKERHUB_USER}/${DOCKERHUB_REPO}:${APP_IMAGE_TAG}-${APP_IMAGE_VER}
                    '''
                    echo "Uploading Done!"
                }
            }
        }
        ////////////////////////////////////////////////////////////////////////////////
        stage('Pipeline Finished!') {
            steps {
                script {
                    FAILED_STAGE = env.STAGE_NAME
                    echo '''-------------------------------------------------------------------------------- 
                      * Stratus Project Pipeline Ended! *             
--------------------------------------------------------------------------------'''
                }
            }
        }
    }
    post {
        success {
            mail to: "${DEFAULT_EMAIL}",
                 subject: "${SUBJECT}: ${currentBuild.currentResult} - ${env.JOB_NAME}",
                 body: "${EMAIL_BODY}: ${env.JOB_NAME}\n${PSTATUS_TAG}: ${currentBuild.currentResult}\n${COMMIT_ID_TAG}: ${env.GIT_COMMIT}\n ${env.BUILD_URL} "
        }
        failure {
            mail to: "${DEFAULT_EMAIL}",
                 subject: "${SUBJECT}: ${currentBuild.currentResult} - ${env.JOB_NAME}",
                 body: "${EMAIL_BODY}: ${env.JOB_NAME}\n${FSTAGE_NAME}: $FAILED_STAGE \n${PSTATUS_TAG}: ${currentBuild.currentResult}\n${COMMIT_ID_TAG}: ${env.GIT_COMMIT}\n${env.BUILD_URL} "
        }
    }
}
